trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'db.properties'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '*.properties'
    TargetFolder: '$(Build.SourcesDirectory)/src/main/resources'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AzurePipeline'
    Contents: '*.properties'
    TargetFolder: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'mysql -u root -proot < $(Build.SourcesDirectory)/Scripts/CupCake_Setup.sql'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)'
    additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'

- task: TomcatDeployment@0
  inputs:
    TomcatUrl: 'http://134.209.233.32'
    Username: '$(username)'
    Password: '$(pwd)'
    Warfile: '$(System.DefaultWorkingDirectory)/target/CupCake.war'
    Context: '/CupCakeDev'
    ServerVersion: '7OrAbove'

- task: CmdLine@2
  inputs:
    script: 'docker network create selenium'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerHub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

- task: CmdLine@2
  inputs:
    script: 'docker run --rm --network=selenium --name maven -v $(System.DefaultWorkingDirectory):/usr/src/mymaven -w /usr/src/mymaven maven:3.6.2-jdk-11 mvn test -Pui-test'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'sonar:sonar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CupCake'
    publishLocation: 'Container'